package config

/** This package contains app wide re-usable constants **/

//BaseURL ...
var BaseURL = "https://zouq.cx"

//MatchFailed ...
var MatchFailed = "No record matching that email and password combination!"

//SignInSuccess ...
var SignInSuccess = "Sign In Successful!"

//EmailNotAvailable ...
var EmailNotAvailable = "Email not available. Please choose another one!"

//FailedToCreateUser ...
var FailedToCreateUser = "Registration failed. An error occurred!"

//SignUpSubject ...
var SignUpSubject = "Welcome To Zouq"

//PasswordRecoverySubject ...
var PasswordRecoverySubject = "Password Recovery"

//GeneralSenderEmail ...
var GeneralSenderEmail = "no-reply@zouq.cx"

//InfoSenderEmail ...
var InfoSenderEmail = "info@zouq.cx"

//ServicesSenderEmail ...
var ServicesSenderEmail = "services@zouq.cx"

//VerificationURL ...
var VerificationURL = BaseURL+"/verify?u="

//RecoveryURL ...
var RecoveryURL = BaseURL+"/change-password?u="

//CantSendEmail ...
var CantSendEmail = "Can't send email. An error occurred!"

//EmailSent ...
var EmailSent = "Email sent successfully!"

//EmailSentRecovery ...
var EmailSentRecovery = "Success! If this account exists, a recovery email would be sent to it!"

//InvalidUser ...
var InvalidUser = "Invalid user!"

//SignUpSuccess ...
var SignUpSuccess = "SignUp Successful!"

//LoginSuccess ...
var LoginSuccess = "Login Successful!"

//UpdateSuccess ...
var UpdateSuccess = "Update Successful!"

//InvalidID ...
var InvalidID = "Invalid user_id supplied!"

//ErrorMSG ...
var ErrorMSG = "Operation not successful. An error occurred!"

//InvalidToken ...
var InvalidToken = "Invalid token!"

//TokenValid ...
var TokenValid = "Token is valid!"

//AccountVerified ...
var AccountVerified = "Account verification successful! You can go back to the app now."

//AccountPendingVerification ...
var AccountPendingVerification = "Your account has not been verified yet!"

//AccountVerificationSuccess ...
var AccountVerificationSuccess = "Account verification successful!"